/* Additional record code for tmp_one_port generated by the OpenModelica Compiler OpenModelica v1.26.3 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "tmp_one_port_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define TmpOnePort_retSink_Medium_ThermodynamicState__desc_added 1
const char* TmpOnePort_retSink_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description TmpOnePort_retSink_Medium_ThermodynamicState__desc = {
  "TmpOnePort_retSink_Medium_ThermodynamicState", /* package_record__X */
  "TmpOnePort.retSink.Medium.ThermodynamicState", /* package.record_X */
  TmpOnePort_retSink_Medium_ThermodynamicState__desc__fields
};

void TmpOnePort_retSink_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  TmpOnePort_retSink_Medium_ThermodynamicState* ths = (TmpOnePort_retSink_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void TmpOnePort_retSink_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  TmpOnePort_retSink_Medium_ThermodynamicState* dst = (TmpOnePort_retSink_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void TmpOnePort_retSink_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  TmpOnePort_retSink_Medium_ThermodynamicState* src = (TmpOnePort_retSink_Medium_ThermodynamicState*)(v_src);
  TmpOnePort_retSink_Medium_ThermodynamicState* dst = (TmpOnePort_retSink_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define TmpOnePort_roo_air_Medium_ThermodynamicState__desc_added 1
const char* TmpOnePort_roo_air_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description TmpOnePort_roo_air_Medium_ThermodynamicState__desc = {
  "TmpOnePort_roo_air_Medium_ThermodynamicState", /* package_record__X */
  "TmpOnePort.roo.air.Medium.ThermodynamicState", /* package.record_X */
  TmpOnePort_roo_air_Medium_ThermodynamicState__desc__fields
};

void TmpOnePort_roo_air_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  TmpOnePort_roo_air_Medium_ThermodynamicState* ths = (TmpOnePort_roo_air_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void TmpOnePort_roo_air_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  TmpOnePort_roo_air_Medium_ThermodynamicState* dst = (TmpOnePort_roo_air_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void TmpOnePort_roo_air_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  TmpOnePort_roo_air_Medium_ThermodynamicState* src = (TmpOnePort_roo_air_Medium_ThermodynamicState*)(v_src);
  TmpOnePort_roo_air_Medium_ThermodynamicState* dst = (TmpOnePort_roo_air_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState__desc_added 1
const char* TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState__desc = {
  "TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState", /* package_record__X */
  "TmpOnePort.roo.air.fluInt.Medium.ThermodynamicState", /* package.record_X */
  TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState__desc__fields
};

void TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState* ths = (TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState* dst = (TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState* src = (TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState*)(v_src);
  TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState* dst = (TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define TmpOnePort_sup_Medium_ThermodynamicState__desc_added 1
const char* TmpOnePort_sup_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description TmpOnePort_sup_Medium_ThermodynamicState__desc = {
  "TmpOnePort_sup_Medium_ThermodynamicState", /* package_record__X */
  "TmpOnePort.sup.Medium.ThermodynamicState", /* package.record_X */
  TmpOnePort_sup_Medium_ThermodynamicState__desc__fields
};

void TmpOnePort_sup_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  TmpOnePort_sup_Medium_ThermodynamicState* ths = (TmpOnePort_sup_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void TmpOnePort_sup_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  TmpOnePort_sup_Medium_ThermodynamicState* dst = (TmpOnePort_sup_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void TmpOnePort_sup_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  TmpOnePort_sup_Medium_ThermodynamicState* src = (TmpOnePort_sup_Medium_ThermodynamicState*)(v_src);
  TmpOnePort_sup_Medium_ThermodynamicState* dst = (TmpOnePort_sup_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}

#ifdef __cplusplus
}
#endif

