/* Simulation code for TmpOnePort generated by the OpenModelica Compiler OpenModelica v1.26.3 (64-bit). */
#if !defined(tmp_one_port__MODEL_H)
#define tmp_one_port__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "tmp_one_port_functions.h"

#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getAbsolutePath_index 0
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getAltitudeLocationTMY3_index 1
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getHeaderElementTMY3_index 2
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getLastHeaderElementTMY3_index 3
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getLatitudeTMY3_index 4
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getLongitudeTMY3_index 5
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getTimeSpanTMY3_index 6
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getTimeZoneTMY3_index 7
#define Buildings_ThermalZones_Detailed_BaseClasses_cfdExchangeData_index 8
#define Buildings_ThermalZones_Detailed_BaseClasses_cfdStartCosimulation_index 9
#define Buildings_ThermalZones_Detailed_BaseClasses_CFDThread_constructor_index 10
#define Buildings_ThermalZones_Detailed_BaseClasses_CFDThread_destructor_index 11
#define Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmax_index 12
#define Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmin_index 13
#define Modelica_Blocks_Tables_Internal_getTable1DValue_index 14
#define Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index 15
#define Modelica_Blocks_Types_ExternalCombiTable1D_destructor_index 16
#define Modelica_Fluid_Utilities_checkBoundary_index 17
#define Modelica_Math_BooleanVectors_anyTrue_index 18
#define Modelica_Math_Vectors_norm_index 19
#define Modelica_Math_Vectors_toString_index 20
#define Modelica_Utilities_Streams_error_index 21
#define Modelica_Utilities_Streams_readLine_index 22
#define Modelica_Utilities_Strings_compare_index 23
#define Modelica_Utilities_Strings_find_index 24
#define Modelica_Utilities_Strings_findLast_index 25
#define Modelica_Utilities_Strings_isEmpty_index 26
#define Modelica_Utilities_Strings_isEqual_index 27
#define Modelica_Utilities_Strings_length_index 28
#define Modelica_Utilities_Strings_repeat_index 29
#define Modelica_Utilities_Strings_substring_index 30
#define Modelica_Utilities_Strings_Advanced_scanReal_index 31
#define Modelica_Utilities_Strings_Advanced_skipWhiteSpace_index 32
#define TmpOnePort_retSink_Medium_ThermodynamicState_index 33
#define TmpOnePort_roo_air_Medium_ThermodynamicState_index 34
#define TmpOnePort_roo_air_cfd_assertStringsAreUnique_index 35
#define TmpOnePort_roo_air_cfd_exchange_index 36
#define TmpOnePort_roo_air_cfd_returnNonUniqueStrings_index 37
#define TmpOnePort_roo_air_cfd_sendParameters_index 38
#define TmpOnePort_roo_air_fluInt_Medium_ThermodynamicState_index 39
#define TmpOnePort_roo_irRadExc_checkSurfaceAreas_index 40
#define TmpOnePort_roo_irRadGai_checkSurfaceAreas_index 41
#define TmpOnePort_roo_radTem_checkSurfaceAreas_index 42
#define TmpOnePort_sup_Medium_ThermodynamicState_index 43

extern void tmp_one_port_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void tmp_one_port_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void tmp_one_port_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void tmp_one_port_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int tmp_one_port_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int tmp_one_port_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int tmp_one_port_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int tmp_one_port_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int tmp_one_port_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int tmp_one_port_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int tmp_one_port_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int tmp_one_port_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int tmp_one_port_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int tmp_one_port_checkForAsserts(DATA *data, threadData_t *threadData);
extern int tmp_one_port_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int tmp_one_port_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int tmp_one_port_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* tmp_one_port_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* tmp_one_port_relationDescription(int i);
extern void tmp_one_port_function_initSample(DATA *data, threadData_t *threadData);
extern int tmp_one_port_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int tmp_one_port_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int tmp_one_port_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int tmp_one_port_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int tmp_one_port_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int tmp_one_port_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int tmp_one_port_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int tmp_one_port_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int tmp_one_port_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int tmp_one_port_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int tmp_one_port_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int tmp_one_port_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int tmp_one_port_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int tmp_one_port_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* tmp_one_port_linear_model_frame(void);
extern const char* tmp_one_port_linear_model_datarecovery_frame(void);
extern int tmp_one_port_mayer(DATA* data, modelica_real** res, short *);
extern int tmp_one_port_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int tmp_one_port_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int tmp_one_port_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int tmp_one_port_setInputData(DATA *data, const modelica_boolean file);
extern int tmp_one_port_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void tmp_one_port_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void tmp_one_port_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int tmp_one_port_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void tmp_one_port_read_simulation_info(SIMULATION_INFO* simulationData);
extern void tmp_one_port_read_input_fmu(MODEL_DATA* modelData);
extern void tmp_one_port_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int tmp_one_port_inputNames(DATA* data, char ** names);
extern int tmp_one_port_dataReconciliationInputNames(DATA* data, char ** names);
extern int tmp_one_port_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int tmp_one_port_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int tmp_one_port_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int tmp_one_port_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "tmp_one_port_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(tmp_one_port__MODEL_H) */


