/* Additional record code for ForcedConvection_30s generated by the OpenModelica Compiler OpenModelica 1.26.3. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "ForcedConvection_30s_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState__desc_added 1
const char* Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState__desc = {
  "Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.ThermalZones.Detailed.Examples.FFD.ForcedConvection.bouOut.Medium.ThermodynamicState", /* package.record_X */
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState__desc__fields
};

void Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState* ths = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState* dst = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState* src = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState*)(v_src);
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState* dst = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bouOut_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState__desc_added 1
const char* Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState__desc = {
  "Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.ThermalZones.Detailed.Examples.FFD.ForcedConvection.bounIn.Medium.ThermodynamicState", /* package.record_X */
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState__desc__fields
};

void Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState* ths = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState* dst = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState* src = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState*)(v_src);
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState* dst = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_bounIn_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState__desc_added 1
const char* Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState__desc = {
  "Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.ThermalZones.Detailed.Examples.FFD.ForcedConvection.roo.air.Medium.ThermodynamicState", /* package.record_X */
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState__desc__fields
};

void Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState* ths = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState* dst = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState* src = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState*)(v_src);
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState* dst = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState__desc_added 1
const char* Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState__desc = {
  "Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.ThermalZones.Detailed.Examples.FFD.ForcedConvection.roo.air.fluInt.Medium.ThermodynamicState", /* package.record_X */
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState__desc__fields
};

void Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState* ths = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState* dst = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState* src = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState*)(v_src);
  Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState* dst = (Buildings_ThermalZones_Detailed_Examples_FFD_ForcedConvection_roo_air_fluInt_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}

#ifdef __cplusplus
}
#endif

