/* Additional record code for tmp_two_returns_res generated by the OpenModelica Compiler OpenModelica v1.26.3 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "tmp_two_returns_res_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define TmpTwoReturnsRes_ret_Medium_ThermodynamicState__desc_added 1
const char* TmpTwoReturnsRes_ret_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description TmpTwoReturnsRes_ret_Medium_ThermodynamicState__desc = {
  "TmpTwoReturnsRes_ret_Medium_ThermodynamicState", /* package_record__X */
  "TmpTwoReturnsRes.ret.Medium.ThermodynamicState", /* package.record_X */
  TmpTwoReturnsRes_ret_Medium_ThermodynamicState__desc__fields
};

void TmpTwoReturnsRes_ret_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  TmpTwoReturnsRes_ret_Medium_ThermodynamicState* ths = (TmpTwoReturnsRes_ret_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void TmpTwoReturnsRes_ret_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  TmpTwoReturnsRes_ret_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_ret_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void TmpTwoReturnsRes_ret_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  TmpTwoReturnsRes_ret_Medium_ThermodynamicState* src = (TmpTwoReturnsRes_ret_Medium_ThermodynamicState*)(v_src);
  TmpTwoReturnsRes_ret_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_ret_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState__desc_added 1
const char* TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState__desc = {
  "TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState", /* package_record__X */
  "TmpTwoReturnsRes.retRes1.Medium.ThermodynamicState", /* package.record_X */
  TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState__desc__fields
};

void TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState* ths = (TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState* src = (TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState*)(v_src);
  TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_retRes1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState__desc_added 1
const char* TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState__desc = {
  "TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState", /* package_record__X */
  "TmpTwoReturnsRes.retRes2.Medium.ThermodynamicState", /* package.record_X */
  TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState__desc__fields
};

void TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState* ths = (TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState* src = (TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState*)(v_src);
  TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_retRes2_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState__desc_added 1
const char* TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState__desc = {
  "TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState", /* package_record__X */
  "TmpTwoReturnsRes.roo.air.Medium.ThermodynamicState", /* package.record_X */
  TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState__desc__fields
};

void TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState* ths = (TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState* src = (TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState*)(v_src);
  TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_roo_air_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState__desc_added 1
const char* TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState__desc = {
  "TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState", /* package_record__X */
  "TmpTwoReturnsRes.roo.air.fluInt.Medium.ThermodynamicState", /* package.record_X */
  TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState__desc__fields
};

void TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState* ths = (TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState* src = (TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState*)(v_src);
  TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_roo_air_fluInt_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define TmpTwoReturnsRes_sup1_Medium_ThermodynamicState__desc_added 1
const char* TmpTwoReturnsRes_sup1_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description TmpTwoReturnsRes_sup1_Medium_ThermodynamicState__desc = {
  "TmpTwoReturnsRes_sup1_Medium_ThermodynamicState", /* package_record__X */
  "TmpTwoReturnsRes.sup1.Medium.ThermodynamicState", /* package.record_X */
  TmpTwoReturnsRes_sup1_Medium_ThermodynamicState__desc__fields
};

void TmpTwoReturnsRes_sup1_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  TmpTwoReturnsRes_sup1_Medium_ThermodynamicState* ths = (TmpTwoReturnsRes_sup1_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void TmpTwoReturnsRes_sup1_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  TmpTwoReturnsRes_sup1_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_sup1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void TmpTwoReturnsRes_sup1_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  TmpTwoReturnsRes_sup1_Medium_ThermodynamicState* src = (TmpTwoReturnsRes_sup1_Medium_ThermodynamicState*)(v_src);
  TmpTwoReturnsRes_sup1_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_sup1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define TmpTwoReturnsRes_sup2_Medium_ThermodynamicState__desc_added 1
const char* TmpTwoReturnsRes_sup2_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description TmpTwoReturnsRes_sup2_Medium_ThermodynamicState__desc = {
  "TmpTwoReturnsRes_sup2_Medium_ThermodynamicState", /* package_record__X */
  "TmpTwoReturnsRes.sup2.Medium.ThermodynamicState", /* package.record_X */
  TmpTwoReturnsRes_sup2_Medium_ThermodynamicState__desc__fields
};

void TmpTwoReturnsRes_sup2_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  TmpTwoReturnsRes_sup2_Medium_ThermodynamicState* ths = (TmpTwoReturnsRes_sup2_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void TmpTwoReturnsRes_sup2_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  TmpTwoReturnsRes_sup2_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_sup2_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void TmpTwoReturnsRes_sup2_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  TmpTwoReturnsRes_sup2_Medium_ThermodynamicState* src = (TmpTwoReturnsRes_sup2_Medium_ThermodynamicState*)(v_src);
  TmpTwoReturnsRes_sup2_Medium_ThermodynamicState* dst = (TmpTwoReturnsRes_sup2_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}

#ifdef __cplusplus
}
#endif

