/* Additional record code for s000_baseline generated by the OpenModelica Compiler OpenModelica v1.26.3 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "s000_baseline_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Scenario__s000__baseline_dc_MediumA_ThermodynamicState__desc_added 1
const char* Scenario__s000__baseline_dc_MediumA_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description Scenario__s000__baseline_dc_MediumA_ThermodynamicState__desc = {
  "Scenario__s000__baseline_dc_MediumA_ThermodynamicState", /* package_record__X */
  "Scenario_s000_baseline.dc.MediumA.ThermodynamicState", /* package.record_X */
  Scenario__s000__baseline_dc_MediumA_ThermodynamicState__desc__fields
};

void Scenario__s000__baseline_dc_MediumA_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Scenario__s000__baseline_dc_MediumA_ThermodynamicState* ths = (Scenario__s000__baseline_dc_MediumA_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void Scenario__s000__baseline_dc_MediumA_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  Scenario__s000__baseline_dc_MediumA_ThermodynamicState* dst = (Scenario__s000__baseline_dc_MediumA_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void Scenario__s000__baseline_dc_MediumA_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Scenario__s000__baseline_dc_MediumA_ThermodynamicState* src = (Scenario__s000__baseline_dc_MediumA_ThermodynamicState*)(v_src);
  Scenario__s000__baseline_dc_MediumA_ThermodynamicState* dst = (Scenario__s000__baseline_dc_MediumA_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState__desc_added 1
const char* Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState__desc = {
  "Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState", /* package_record__X */
  "Scenario_s000_baseline.dc.retRes.Medium.ThermodynamicState", /* package.record_X */
  Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState__desc__fields
};

void Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState* ths = (Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState* dst = (Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState* src = (Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState*)(v_src);
  Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState* dst = (Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState__desc_added 1
const char* Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState__desc = {
  "Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState", /* package_record__X */
  "Scenario_s000_baseline.dc.retSink.Medium.ThermodynamicState", /* package.record_X */
  Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState__desc__fields
};

void Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState* ths = (Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState* dst = (Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState* src = (Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState*)(v_src);
  Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState* dst = (Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState__desc_added 1
const char* Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState__desc = {
  "Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState", /* package_record__X */
  "Scenario_s000_baseline.dc.roo.air.Medium.ThermodynamicState", /* package.record_X */
  Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState__desc__fields
};

void Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState* ths = (Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState* dst = (Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState* src = (Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState*)(v_src);
  Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState* dst = (Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState__desc_added 1
const char* Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState__desc = {
  "Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState", /* package_record__X */
  "Scenario_s000_baseline.dc.roo.air.fluInt.Medium.ThermodynamicState", /* package.record_X */
  Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState__desc__fields
};

void Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState* ths = (Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState* dst = (Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState* src = (Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState*)(v_src);
  Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState* dst = (Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}


#define Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState__desc_added 1
const char* Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState__desc__fields[3] = {"p","T","X"};
struct record_description Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState__desc = {
  "Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState", /* package_record__X */
  "Scenario_s000_baseline.dc.sup.Medium.ThermodynamicState", /* package.record_X */
  Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState__desc__fields
};

void Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState* ths = (Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  alloc_real_array(&(ths->_X), 1, (_index_t)2); // ths->_X has no default value.
}
void Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, real_array in_X) {
  Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState* dst = (Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_X = in_X;
}

void Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState* src = (Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState*)(v_src);
  Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState* dst = (Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  real_array_copy_data(src->_X, dst->_X);
}

#ifdef __cplusplus
}
#endif

