/* Simulation code for Scenario_s000_baseline generated by the OpenModelica Compiler OpenModelica v1.26.3 (64-bit). */
#if !defined(s000_baseline__MODEL_H)
#define s000_baseline__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "s000_baseline_functions.h"

#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getAbsolutePath_index 0
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getAltitudeLocationTMY3_index 1
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getHeaderElementTMY3_index 2
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getLastHeaderElementTMY3_index 3
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getLatitudeTMY3_index 4
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getLongitudeTMY3_index 5
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getTimeSpanTMY3_index 6
#define Buildings_BoundaryConditions_WeatherData_BaseClasses_getTimeZoneTMY3_index 7
#define Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__m__flow_index 8
#define Buildings_ThermalZones_Detailed_BaseClasses_cfdExchangeData_index 9
#define Buildings_ThermalZones_Detailed_BaseClasses_cfdStartCosimulation_index 10
#define Buildings_ThermalZones_Detailed_BaseClasses_CFDThread_constructor_index 11
#define Buildings_ThermalZones_Detailed_BaseClasses_CFDThread_destructor_index 12
#define Modelica_Blocks_Tables_Internal_getNextTimeEvent_index 13
#define Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmax_index 14
#define Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmin_index 15
#define Modelica_Blocks_Tables_Internal_getTable1DValue_index 16
#define Modelica_Blocks_Tables_Internal_getTimeTableTmax_index 17
#define Modelica_Blocks_Tables_Internal_getTimeTableTmin_index 18
#define Modelica_Blocks_Tables_Internal_getTimeTableValueNoDer_index 19
#define Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index 20
#define Modelica_Blocks_Types_ExternalCombiTable1D_destructor_index 21
#define Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index 22
#define Modelica_Blocks_Types_ExternalCombiTimeTable_destructor_index 23
#define Modelica_Fluid_Utilities_checkBoundary_index 24
#define Modelica_Math_BooleanVectors_anyTrue_index 25
#define Modelica_Math_Vectors_norm_index 26
#define Modelica_Math_Vectors_toString_index 27
#define Modelica_Utilities_Streams_error_index 28
#define Modelica_Utilities_Streams_readLine_index 29
#define Modelica_Utilities_Strings_compare_index 30
#define Modelica_Utilities_Strings_find_index 31
#define Modelica_Utilities_Strings_findLast_index 32
#define Modelica_Utilities_Strings_isEmpty_index 33
#define Modelica_Utilities_Strings_isEqual_index 34
#define Modelica_Utilities_Strings_length_index 35
#define Modelica_Utilities_Strings_repeat_index 36
#define Modelica_Utilities_Strings_substring_index 37
#define Modelica_Utilities_Strings_Advanced_scanReal_index 38
#define Modelica_Utilities_Strings_Advanced_skipWhiteSpace_index 39
#define Scenario__s000__baseline_dc_MediumA_ThermodynamicState_index 40
#define Scenario__s000__baseline_dc_retRes_Medium_ThermodynamicState_index 41
#define Scenario__s000__baseline_dc_retSink_Medium_ThermodynamicState_index 42
#define Scenario__s000__baseline_dc_roo_air_Medium_ThermodynamicState_index 43
#define Scenario__s000__baseline_dc_roo_air_cfd_assertStringsAreUnique_index 44
#define Scenario__s000__baseline_dc_roo_air_cfd_exchange_index 45
#define Scenario__s000__baseline_dc_roo_air_cfd_returnNonUniqueStrings_index 46
#define Scenario__s000__baseline_dc_roo_air_cfd_sendParameters_index 47
#define Scenario__s000__baseline_dc_roo_air_fluInt_Medium_ThermodynamicState_index 48
#define Scenario__s000__baseline_dc_roo_irRadExc_checkSurfaceAreas_index 49
#define Scenario__s000__baseline_dc_roo_irRadGai_checkSurfaceAreas_index 50
#define Scenario__s000__baseline_dc_roo_radTem_checkSurfaceAreas_index 51
#define Scenario__s000__baseline_dc_sup_Medium_ThermodynamicState_index 52

extern void s000_baseline_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void s000_baseline_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void s000_baseline_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void s000_baseline_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int s000_baseline_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int s000_baseline_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int s000_baseline_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int s000_baseline_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int s000_baseline_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int s000_baseline_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int s000_baseline_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int s000_baseline_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int s000_baseline_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int s000_baseline_checkForAsserts(DATA *data, threadData_t *threadData);
extern int s000_baseline_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int s000_baseline_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int s000_baseline_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* s000_baseline_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* s000_baseline_relationDescription(int i);
extern void s000_baseline_function_initSample(DATA *data, threadData_t *threadData);
extern int s000_baseline_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int s000_baseline_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int s000_baseline_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int s000_baseline_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int s000_baseline_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int s000_baseline_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int s000_baseline_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int s000_baseline_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int s000_baseline_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int s000_baseline_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int s000_baseline_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int s000_baseline_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int s000_baseline_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int s000_baseline_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* s000_baseline_linear_model_frame(void);
extern const char* s000_baseline_linear_model_datarecovery_frame(void);
extern int s000_baseline_mayer(DATA* data, modelica_real** res, short *);
extern int s000_baseline_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int s000_baseline_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int s000_baseline_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int s000_baseline_setInputData(DATA *data, const modelica_boolean file);
extern int s000_baseline_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void s000_baseline_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void s000_baseline_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int s000_baseline_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void s000_baseline_read_simulation_info(SIMULATION_INFO* simulationData);
extern void s000_baseline_read_input_fmu(MODEL_DATA* modelData);
extern void s000_baseline_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int s000_baseline_inputNames(DATA* data, char ** names);
extern int s000_baseline_dataReconciliationInputNames(DATA* data, char ** names);
extern int s000_baseline_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int s000_baseline_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int s000_baseline_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int s000_baseline_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "s000_baseline_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(s000_baseline__MODEL_H) */


